# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7e238e072d6f9c257220de695073c8803524517001a0d3a635169badbfb26667fc51d4104e24806402f3ce026ca5f752ae20b6cdb8f6b9210c9c75a81eabfa

test:
  secret_key_base: 9f28bd6aebf5a7e8269bc3da86a2b94dd80d35bd720c1dbf568625235515aa5809cbe162a47cb3d1fb2aaf8742c5ae2f3c6296a1c2c5e6ad5c7f3f4c6b860327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
